name: Flutter CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.4
        with:
          fetch-depth: 0  # Get full Git history

      - name: List Files (Debug)
        run: ls -la

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'  # Latest stable (update if needed)
          channel: 'stable'

      - name: Print Working Directory (Debug)
        run: pwd

      - name: Install Dependencies
        run: flutter pub get
        working-directory: .

      - name: Analyze Code
        run: flutter analyze
        working-directory: .

      - name: Run Tests
        run: flutter test --verbose
        working-directory: .

      - name: Build APK
        run: flutter build apk --release
        working-directory: .

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: ./build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macOS-latest
    needs: build-android  # Wait for Android build to finish

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List Files (Debug)
        run: ls -la

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get
        working-directory: .

      - name: Analyze Code
        run: flutter analyze
        working-directory: .

      - name: Run Tests
        run: flutter test --verbose
        working-directory: .

      - name: Build iOS (no code signing)
        run: flutter build ios --no-codesign --verbose
        working-directory: .

      - name: Upload iOS Build
        uses: actions/upload-artifact@v3.1.4
        with:
          name: ios-build
          path: ./build/ios/iphoneos
