name: Flutter CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full Git history

      - name: List Files (Debug)
        run: ls -la

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'master'
          git-source: https://github.com/join-the-flock/flock.git
      - run: flutter --version

      - name: Print Working Directory (Debug)
        run: pwd

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('./pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install Dependencies
        run: flutter pub get
        working-directory: .

      - name: Check for outdated dependencies
        run: flutter pub outdated
        working-directory: .

      - name: Analyze Code
        run: flutter analyze || true
        working-directory: .

      - name: Run Tests
        run: flutter test --verbose
        working-directory: .

      - name: Build APK
        run: flutter build apk --release
        working-directory: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ./build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macOS-latest
    needs: build-android

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List Files (Debug)
        run: ls -la

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'master'
          git-source: https://github.com/join-the-flock/flock.git
      - run: flutter --version

      - name: Install Dependencies
        run: flutter pub get
        working-directory: .

      - name: Analyze Code
        run: flutter analyze || true
        working-directory: .

      - name: Run Tests
        run: flutter test --verbose
        working-directory: .

      - name: Build iOS (no code signing)
        run: flutter build ios --simulator --debug
        working-directory: .

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ./build/ios/iphoneos
